### ISSUE TITLE
Some classes when registered cause errors in the moonsharp side

### ISSUE THREAD

**Issue by evilfactory** [evilfactory/Barotrauma-lua-attempt#39]
```lua
LuaUserData.RegisterType('Barotrauma.HumanoidAnimController')
```

This causes to throw the following error:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Multiple members named CurrentGroundedParams are being added to type Barotrauma.HumanoidAnimController and one or more of these members do not support overloads.
   at MoonSharp.Interpreter.Interop.BasicDescriptors.DispatchingUserDataDescriptor.AddMemberTo(Dictionary`2 members, String name, IMemberDescriptor desc)
   at MoonSharp.Interpreter.Interop.StandardUserDataDescriptor.FillMemberList()
   at MoonSharp.Interpreter.Interop.StandardUserDataDescriptor..ctor(Type type, InteropAccessMode accessMode, String friendlyName)
   at MoonSharp.Interpreter.Interop.UserDataRegistries.TypeDescriptorRegistry.RegisterType_Impl(Type type, InteropAccessMode accessMode, String friendlyName, IUserDataDescriptor descriptor)
   at MoonSharp.Interpreter.UserData.RegisterType[T](InteropAccessMode accessMode, String friendlyName)
   ```

**Comment by evilfactory** [comment]
Now with the fork of Moonsharp, i can probably fix this bug.

**Comment by evilfactory** [comment]
Fixed in unstable
